#!/bin/sh

case $1 in
	mem)
		text=$(free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }')
		icon=/usr/share/icons/Adwaita/16x16/mimetypes/application-x-firmware.png
		;;
	disk)
		text=$(df -h | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')
		icon=/usr/share/icons/gnome/16x16/devices/drive-harddisk.png
		;;
	load)
		text=$(top -bn1 | grep load | awk '{printf "%.2f\n", $(NF-2)}')
		icon=/usr/share/icons/gnome/16x16/devices/gnome-dev-battery.png
		;;
esac
echo "<img>$icon</img><txt> $text</txt>"
