#!/bin/sh

case $1 in
	mem)
		text=$(free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)", $3,$2,$3*100/$2 }')
		icon=/usr/share/icons/Adwaita/16x16/mimetypes/application-x-firmware.png
		click="xfce4-terminal --command=htop"
		;;
	disk)
		text=$(df -h | awk '$NF=="/"{printf "%d/%dGB (%s)", $3,$2,$5}')
		icon=/usr/share/icons/gnome/16x16/devices/drive-harddisk.png
		tooltip=$(df -h | colrm 1 33)
		click="xfce4-terminal --command=df"
		;;
	load)
		text=$(top -bn1 | grep load | awk '{printf "%.2f  %.2f",$(NF-2),$(NF-1)}')
		icon=/usr/share/icons/gnome/16x16/devices/gnome-dev-battery.png
		tooltip=$(top -bn1 | grep load)
		click="xfce4-terminal --command=htop"
		;;
esac
echo "<img>$icon</img><txt> $text</txt><tool>$tooltip</tool><txtclick>$click</txtclick>"
