#!/bin/bash

[ -z "$(pidof i3lock)" ] || { echo "Already running"; exit; } 

pkill unclutter
notify-send "DUNST_COMMAND_PAUSE" &

i3lock-fancy-rapid 3 5 -n

unclutter -b
notify-send "DUNST_COMMAND_RESUME" &
