#!/bin/bash

[ -z "$(pidof i3lock)" ] || { echo "Already running"; exit; } 

pkill unclutter
notify-send "DUNST_COMMAND_PAUSE"

SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
for RES in $SR; do
  SRA=(${RES//[x+]/ })
  CX=$((${SRA[2]} + 25))
  CY=$((${SRA[1]} - 50))
  rectangles+="rectangle $CX,$CY $((CX+300)),$((CY-80)) "
done

TMPBG=/tmp/screen.png
scrot $TMPBG && convert $TMPBG -scale 5% -scale 2000% -draw "fill black fill-opacity 0.4 $rectangles" $TMPBG

letterEnteredColor=d23c3dff
letterRemovedColor=d23c3dff
passwordCorrect=00000000
passwordIncorrect=d23c3dff
background=00000000
foreground=ffffffff

i3lock \
   -t -n -i "$TMPBG" --indicator \
   --clock --datestr "Type password to unlock..." \
   --timecolor="$foreground" --timecolor="$foreground" --datecolor="$foreground" \
   --radius=20 --ring-width=4 --veriftext="" --wrongtext="" \
   --insidecolor=$background --ringcolor=$foreground --line-uses-inside \
   --keyhlcolor=$letterEnteredColor --bshlcolor=$letterRemovedColor --separatorcolor=$background \
   --insidevercolor=$passwordCorrect --insidewrongcolor=$passwordIncorrect \
   --ringvercolor=$foreground --ringwrongcolor=$foreground \
   --indpos="280:h-340" \
   --timepos="ix-180:iy" \
   --timesize=24 \
   --datepos="tx+28:ty+25" \

unclutter -b
notify-send "DUNST_COMMAND_RESUME"
